### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'gdb_path'

### ISSUE THREAD

**Issue by visionius** [angr/angr-targets#8]
Hi. I just install the angr-targets and I want to use  this:
`avatar_gdb = AvatarGDBConcreteTarget(avatar2.archs.x86.X86_64, GDB_SERVER_IP, GDB_SERVER_PORT)`

The full error texts is here:
Exception ignored in: <bound method GDBProtocol.__del__ of <avatar2.protocols.gdb.GDBProtocol object at 0x7f2e606b75c0>>
Traceback (most recent call last):
  File "/home/lab-test/.local/lib/python3.6/site-packages/avatar2/protocols/gdb.py", line 287, in __del__
    self.shutdown()
  File "/home/lab-test/.local/lib/python3.6/site-packages/avatar2/protocols/gdb.py", line 290, in shutdown
    if self._communicator is not None:
AttributeError: 'GDBProtocol' object has no attribute '_communicator'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab-test/Downloads/angr_targets/angr-targets/angr_targets/targets/avatar_gdb.py", line 23, in __init__
    self.avatar.init_targets()
  File "/home/lab-test/.local/lib/python3.6/site-packages/avatar2/avatar2.py", line 210, in init_targets
    t[1].init()
  File "/home/lab-test/.local/lib/python3.6/site-packages/avatar2/targets/gdb_target.py", line 47, in init
    verbose=self._verbose_gdbmi)
  File "/home/lab-test/.local/lib/python3.6/site-packages/avatar2/protocols/gdb.py", line 273, in __init__
    verbose=verbose)  # set to True for debugging
TypeError: __init__() got an unexpected keyword argument 'gdb_path'

I am using ubuntu 18 and try to pass that 'avatar_gdb' as a ConcreteTarget in angr.

**Comment by visionius** [comment]
Simply remove all 3 lines in lib/python3.6/site-packages/avatar2/protocols/gdb.py:

`            gdb_path=gdb_executable,
            gdb_args=gdb_args,
            verbose=verbose)  # set to True for debugging
 `
pfffffff...
