### ISSUE TITLE
GDBProtocol was unable to connect 

### ISSUE THREAD

**Issue by sh4m2hwz** [angr/angr-targets#9]
```
avatar_gdb = AvatarGDBConcreteTarget(avatar2.archs.x86.X86,"127.0.0.1", 1234)
CRITICAL | 2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
2021-01-12 07:11:52,893 | avatar.targets.GDBTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python3.9/dist-packages/angr_targets/targets/avatar_gdb.py", line 23, in init
self.avatar.init_targets()
File "/usr/local/lib/python3.9/dist-packages/avatar2/avatar2.py", line 222, in init_targets
t[1].init()
File "/usr/local/lib/python3.9/dist-packages/avatar2/targets/gdb_target.py", line 53, in init
if gdb.remote_connect(ip=self.gdb_ip, port=self.gdb_port):
File "/usr/local/lib/python3.9/dist-packages/avatar2/protocols/gdb.py", line 379, in remote_connect
raise Exception("GDBProtocol was unable to connect")
Exception: GDBProtocol was unable to connect`
--------------------------------------------
Attached; pid = 18032
Listening on port 1234
Remote debugging from host 127.0.0.1
```

**Comment by degrigis** [comment]
Sorry for the super-late answer, can you provide me more context on this? Have you started the program under a gdbserver before running your script? :)

**Comment by nkawa94** [comment]
I had the same problem. I wanted to reimplement the basic example on qemu_uboot using my own kernel and a qemu raw image containing the system files of a firmware. You can see my error below :

2021-06-08 15:45:57,239 | avatar.targets.QemuTarget0.GDBProtocol.CRITICAL | GDBProtocol was unable to connect to remote target
Traceback (most recent call last):
  File "Test_avatar.py", line 111, in <module>
    main()
  File "Test_avatar.py", line 85, in main
    avatar.init_targets()
  File "/usr/local/lib/python3.8/dist-packages/avatar2-1.4.5-py3.8.egg/avatar2/avatar2.py", line 233, in init_targets
    t[1].init()
  File "/usr/local/lib/python3.8/dist-packages/avatar2-1.4.5-py3.8.egg/avatar2/watchmen.py", line 78, in watchtrigger
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/avatar2-1.4.5-py3.8.egg/avatar2/targets/qemu_target.py", line 262, in init
    self._connect_protocols()
  File "/usr/local/lib/python3.8/dist-packages/avatar2-1.4.5-py3.8.egg/avatar2/targets/qemu_target.py", line 297, in _connect_protocols
    if gdb.remote_connect(port=self.gdb_port) and qmp.connect():
  File "/usr/local/lib/python3.8/dist-packages/avatar2-1.4.5-py3.8.egg/avatar2/protocols/gdb.py", line 389, in remote_connect
    raise Exception("GDBProtocol was unable to connect")
Exception: GDBProtocol was unable to connect

**Comment by PBHDK** [comment]
@sh4m2hwz @nkawa94, did any of you end up solving this problem?

**Comment by Kang-Sir-C** [comment]
@paulhdk Hello, did you solve this problem?
